Windows-on-ARM-Experiments/mingw-woarm64-build

.github/workflows/main.yml
build.sh

It will have to be merged before it could be tested. We can test, amend the fix and force push the fix if needed.

Add workflow_dispatch with branch name parameters

---

build.sh

Remove redundant mkdir

---

tests/build-tests.sh

Allows building tests for different toolchain variants more easily by changing variables inside the script.

Allow building tests with different toolchain variants

---

.github/workflows/advanced.yml

I am not sure how we could miss that... but YOLO.

Fix cache key

---

.github/cmake/aarch64-linux-gnu.cmake
.github/scripts/binutils/build.sh
.github/scripts/build.sh
.github/scripts/config-mingw.sh
.github/scripts/config.sh
.github/scripts/ffmpeg/build.sh
.github/scripts/ffmpeg/execute-tests.sh
.github/scripts/libjpeg-turbo/build.sh
.github/scripts/libxml2/build.sh
.github/scripts/openblas/build.sh
.github/scripts/openssl/build.sh
.github/scripts/toolchain/build-gcc-libs.sh
.github/scripts/toolchain/build-gcc.sh
.github/scripts/toolchain/build-libgcc.sh
.github/scripts/toolchain/build-mingw-crt.sh
.github/scripts/toolchain/build-mingw-headers.sh
.github/scripts/toolchain/build-mingw.sh
.github/scripts/zlib/build.sh
build.sh

Fix local build of `aarch64-linux-gnu` target and add possibility to build build libraries for that target using CMake

Fix local build of `aarch64-linux-gnu` target and add possibility to build build libraries for that target using CMake

---

.github/workflows/advanced.yml

This resolves regression in running OpenBLAS tests.

Use stable OpenBLAS version

---

.github/scripts/binutils/build.sh
.github/scripts/install-dependencies.sh
.github/scripts/install-libraries.sh
.github/scripts/toolchain/build-gcc-libs.sh
.github/scripts/toolchain/build-gcc.sh
.github/scripts/toolchain/build-libgcc.sh
.github/scripts/toolchain/build-mingw-crt.sh
.github/scripts/toolchain/build-mingw-headers.sh
.github/scripts/toolchain/build-mingw.sh
.github/scripts/toolchain/unpack.sh

Just unifies the indentation. As the further PRs will modify or remove lot of the toolchain build scripts, having those formatting changes separately approve might make the review easier.

Unify indentation of code blocks inside GitHub `echo` groups

---

.github/scripts/binutils/build.sh
.github/scripts/binutils/patch-cygwin.sh
.github/scripts/build.sh
.github/scripts/config.sh
.github/scripts/install-dependencies.sh
.github/scripts/toolchain/build-cocom.sh
.github/scripts/toolchain/build-cygwin.sh
.github/scripts/toolchain/build-gcc-stage1.sh
.github/scripts/toolchain/build-gcc.sh
.github/scripts/toolchain/build-mingw-crt.sh
.github/scripts/toolchain/build-mingw-headers.sh
.github/scripts/toolchain/build-mingw.sh
.github/scripts/toolchain/install-cygwin-headers.sh
.github/scripts/toolchain/patch-cygwin.sh
.github/workflows/advanced.yml
patches/cygwin/0001-before-autogen.patch
patches/cygwin/0002-after-autogen.patch
patches/cygwin/0003-master.patch

Adds Cygwin and `x86_64-pc-cygwin` GCC build to the `advanced.yml` workflow.

Add `x86_64-pc-cygwin` target to `advanced.yml`

---

.github/workflows/advanced.yml

... to unblock the development and daily rebases.

Pin OpenBLAS repo to latest known stable version

---

.gitignore

Just adds the VSCode workspace file to the .gitignore

Add VSCode workspace file to .gitignore

---

.github/scripts/binutils/build.sh
.github/scripts/build.sh
.github/scripts/config.sh
.github/scripts/ffmpeg/build.sh
.github/scripts/libjpeg-turbo/build.sh
.github/scripts/libxml2/build.sh
.github/scripts/openblas/build.sh
.github/scripts/openssl/build.sh
.github/scripts/toolchain/build-cocom.sh
.github/scripts/toolchain/build-cygwin.sh
.github/scripts/toolchain/build-gcc-stage1.sh
.github/scripts/toolchain/build-gcc.sh
.github/scripts/toolchain/build-mingw-crt.sh
.github/scripts/toolchain/build-mingw-headers.sh
.github/scripts/toolchain/build-mingw-winpthreads.sh
.github/scripts/toolchain/build-mingw.sh
.github/scripts/toolchain/patch-cygwin.sh
.github/scripts/update-sources.sh
.github/scripts/zlib/build.sh

Bash's `if [[ ]]` supports more features that `if []`. This PR unifies the usage in favor of the more robust option.

Unify syntax of Bash conditions

---

.github/workflows/main.yml

Fixes warnings during workflow runs.

Update deprecated GitHub Actions

---

tests/CMakeLists.txt
tests/large-alignment-test.c
tests/main.c

https://github.com/Windows-on-ARM-Experiments/gcc-woarm64/pull/29

Add test for large alignments

---

.github/scripts/binutils/patch-cygwin.sh
.github/scripts/build.sh
.github/scripts/toolchain/patch-cygwin.sh
.github/scripts/update-sources.sh

Fixes the way when and how are git source codes reset.

Fix source code resetting

---

.github/scripts/build.sh
.github/scripts/config.sh

This is useful when building locally.

Add possibility to skip source code patching phase

---

.github/workflows/advanced.yml

Enables ccache for `advanced.yml`.
Depends on https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/pull/172.

Enable ccache for `advanced.yml`

---

.github/scripts/config.sh

The change helps to support different host architectures.

Add support for different host architectures

---

.github/workflows/build-and-test-toolchain.yml
.github/workflows/test-toolchain.yml

Fixes workflow names so it should be more obvious what is each workflow good for.

Fix ambiguity in workflow names

---

tools/gcc.natvis

This Natvis config file can be used to debug Linux host GCC in VSCode using GDB integration. Just reference it in your  `launch.json` VSCode debugging configuration file:
```
{
"name": "<name>",
"type": "cppdbg",
"request": "launch",
"program": "<command>",
"args": [
"<arg1>"
],
"visualizerFile": "${workspaceFolder}/tools/gcc.natvis",
"cwd": "${workspaceFolder}",
...
},
```

Add Natvis configuration file for easier GCC debugging

---

tests/cygwin/hello-cygwin.c

Validate a SIGFE workaround and use printf for testing cygwin
https://github.com/Windows-on-ARM-Experiments/newlib-cygwin/pull/7
Validated by
https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/actions/runs/12995166412

Validate a SIGFE workaround and use printf for testing cygwin

---

.github/scripts/config.sh
.github/workflows/advanced.yml

more information here
https://github.com/madler/zlib/issues/1038

Switch to the master branch after a regression in the develop branch

---

.github/scripts/git-utils.sh
.github/scripts/rebase-clean.sh
.github/scripts/rebase-finish.sh
.github/scripts/rebase-start.sh
.github/scripts/update-sources.sh
.github/workflows/rebase.yml

Adds additional check if `woarm64` branch has not changed during the daily rebase.

Add check if main branch has not changed to `rebase.yml`

---

.github/scripts/toolchain/execute-cygwin-tests.sh

Allows to run single or multiple Cygwin tests, example:
```
.githubs/scripts/toolchain/execute-cygwin-tests.sh samples/sample-pass
```
or 
```
.githubs/scripts/toolchain/execute-cygwin-tests.sh samples/sample-pass samples/sample-failure
```

Allow to run single or multiple Cygwin tests
