.github/workflows/main.yml, install-dependencies.sh
This makes build and installation jobs of the GHA workflow somewhat consistent.
=> Refactor installation job to be consistent with build.sh

build.sh
Makes CI log slightly better readable by using groups, e.g. https://github.com/ZacWalk/mingw-woarm64-build/actions/runs/5576924316/jobs/10188914065. Enables shell commands printing.
=> Set shell verbose output and group log messages by jobs

.github/scripts/build-mingw-crt.sh, .github/scripts/build-mingw-headers.sh, .github/scripts/build-mingw.sh, .github/scripts/build.sh, .github/workflows/advanced.yml, .gitignore
Adds `x86_64-w64-mingw32` and `ucrt` builds.
Depends on #39 that needs to be merged first.
Closes https://github.com/ZacWalk/mingw-woarm64-build/issues/36, https://github.com/ZacWalk/mingw-woarm64-build/issues/22
=> Add other build variants

.github/scripts/build-binutils.sh, .github/scripts/build-gcc-libs.sh, .github/scripts/build-gcc.sh, .github/scripts/build-libgcc.sh, .github/scripts/build-mingw-crt.sh, .github/scripts/build-mingw-headers.sh, .github/scripts/build-mingw.sh, .github/scripts/build.sh, .github/scripts/config-mingw.sh, .github/scripts/config.sh, .github/scripts/install-dependencies.sh, .github/scripts/install-libraries.sh
Refactors configuration of advanced worflow build scritps so it can be shared across them.
=> Share same config between build scripts

.github/scripts/pack-toolchain-mock.sh, .github/scripts/pack-toolchain.sh, .github/workflows/advanced.yml
Creates empty archive for toolchain variants that won't be ever used. This still allows to leverage the caching.
=> Skip toolchain packing for toolchains that are not needed

.github/scripts/build-openblas.sh, .github/scripts/rebase-finish.sh, .github/scripts/rebase-start.sh, .github/workflows/advanced.yml, .github/workflows/main.yml, .github/workflows/rebase.yml
Attempts to rebase binutils, GCC and MinGW repositories to upstream `master` branches, then triggers the advanced worflow and if it suceeds, finishes the rebase by overwriting `woarm64` branches. If the build fails the `rebase-upstream` branches will contain the rebase results.
https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/pull/74/commits/a66d57d4c5dfedbe126e1b74e3b1d003a13dd24e commit will be removed before merge.
=> Add workflow for automatic rebase of dependencies repositories

.github/workflows/advanced.yml, patches/ffmpeg/fate.patch
Lets use stable FFmpeg to avoid unnecessaring regressions in tests like https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/actions/runs/7691458527/job/20965400192.
This PR is needed to fix automatic rebases.
=> Use stable branch for FFmpeg testing

.github/scripts/ffmpeg/build.sh
Enables build optimizations of FFmpeg but disables sin and cos builtin functions using which suffer with `cexp` optimization issue.
=> Enable FFmpeg optimizations

.github/workflows/advanced.yml, .github/workflows/rebase.yml
This change will allow us to manually promote the result of a daily updates workflow to a release. This should help users of our toolchain to more easily access the binaries.
The workflow run demonstrating how it looks like is https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/actions/runs/7830612468
=> Add manual release step to daily updates workflow

.github/scripts/build.sh, .github/scripts/config-mingw.sh, .github/scripts/config.ps1, .github/scripts/config.sh, .github/scripts/toolchain/build-gcc.sh, .github/workflows/advanced.yml
This adds further versatility for the builds scripts for decisions how the `configure` options should be constructed.
=> Split `TARGET` into `ARCH` and `PLATFORM`

.github/scripts/binutils/build.sh, .github/scripts/config-mingw.sh, .github/scripts/ffmpeg/build.sh, .github/scripts/toolchain/build-gcc.sh, .github/scripts/toolchain/build-mingw-crt.sh, .github/scripts/toolchain/build-mingw-headers.sh, .github/scripts/toolchain/build-mingw.sh
Unifies how the host and target `configure` options are constructed. This refactor will be heavily used for Cygwin build.
=> Unify how the host and target `configure` options are constructed

.github/workflows/build-and-test-toolchain.yml, .github/workflows/test-toolchain.yml
Increases retention of GCC regression tests artifacts to 30 days.
=> Increase retention to 30 days for GCC regression tests

.github/workflows/build-and-test-toolchain.yml
Hopefully fixes the situation that for `workflow_dispatch` on `main` branch the `github.head_ref` is empty. Cannot be tested until in the `main` though.
=> Fix default branch for `workflow_dispatch`

.github/workflows/advanced.yml
Rather use main branch Cygwin as the aarch64 differences will be applied as patches. Also, fixes the default branch for COCOM to `master` from `main` which does not exist. Next step could be adding automatic synchronization with upstream to `rebase.yml` (not in this PR though).
=> Use main branch for Cygwin as default

.github/scripts/toolchain/compare-gcc-results.sh
Fixes pipeline fail when `compare-gcc-results.sh` detected regressions.
=> Do not fail pipeline when compare-gcc-results.sh discovers differences

.github/workflows/test-toolchain.yml
This explains weird regressions detected during patch set testing.
=> Fix baseline GCC and MinGW branch for test-toolchain.yml

.github/scripts/build.sh, .github/scripts/install-dependencies.sh, .github/workflows/advanced.yml
Fixes issue that `.github/scripts/binutils/patch-cygwin.sh` and `.github/scripts/toolchain/patch-cygwin.sh` scripts reset the repositories and thus remove the symlinks.
=> Fix dependency symlinks for `*-pc-cygwin` targets

.github/workflows/advanced.yml, patches/ffmpeg/fate.patch, tests/CMakeLists.txt, tests/large-struct-test.c, tests/main.c, tests/static-function-test.c, tests/static-function.c
Validate fixes to resolve the following issues
Relocation overflow when struct is large
https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/issues/130
Relocation overflow issue when building FFmpeg with -O3
https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/issues/100
Building OpenBLAS develop branch
Relocations and small code model fixes
a static function call by reference from another object file.
=> Test relocation and small code model fixes

tests/CMakeLists.txt, tests/main.c, tests/weak-references-test.c, tests/weak-references.c
This change validates weak references support after following fixes.
[Support relocation for weak references](https://github.com/Windows-on-ARM-Experiments/binutils-woarm64/pull/4)
[Support weak references](https://github.com/Windows-on-ARM-Experiments/gcc-woarm64/pull/28)
=> Add tests to validate weak references

.github/workflows/build-and-test-toolchain.yml
`github.head_ref` is valid only for `pull_request` trigger, for `worflow_dispatch` trigger the `github.ref_name` should be used.
=> Fix repository branch when the `build-and-test-toolchain.yml` workflow is triggered manually

.github/scripts/build.sh, .github/scripts/config.sh, .github/scripts/enable-ccache.sh, .github/scripts/toolchain/execute-gcc-tests.sh
This is a small refactoring that will be used for adding MSYS2 specific ccache enablement. It also disables ccache for testing - only MSYS2 has an issue related to that but, in general, caching during testing might be quite dangerous.
Tested by https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/actions/runs/10218137685
=> Move ccache enablement into a separate script

.github/workflows/main.yml
Enables ccache for `main.yml` workflow. Similar changes for other workflows will follow albeit the cache won't be shared.
Depends on https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/pull/159
=> Enable ccache for `main.yml`

.github/workflows/build-and-test-toolchain.yml
The previous state was just a workaround. Now I've figured out how it should be done properly.
Tested by https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/actions/runs/10265560530
=> Fix the way how environment variables are injected into WSL environment

.github/scripts/toolchain/execute-gcc-tests.sh, .github/workflows/build-and-test-toolchain.yml
Adds options to `execute-gcc-tests.sh` script for selecting single GCC module, GCC tests filter, and DejaGNU target and host boards.
Tested by https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/actions/runs/10265746800
=> Add option to select single GCC module, tests filter, and target and host boards to `execute-gcc-tests.sh`

.github/scripts/toolchain/create-gcc-summary.sh, .github/workflows/build-and-test-toolchain.yml
Shows nice test results summaries in the testing job GitHub Actions summary.
Tested by https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/actions/runs/10267629249
=> Output test results summaries into `$GITHUB_STEP_SUMMARY`

.github/workflows/build-and-test-toolchain.yml, .gitignore
Enables ccache for `build-and-test-toolchain.yml` workflow.
Depends on other changes, only the last commit cf2462f is relevant. Will be rebased once the dependent changes will be merged.
Tested by https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/actions/runs/10270801421
=> Enable ccache for `build-and-test-toolchain.yml`

.github/scripts/binutils/build.sh, .github/scripts/config.sh, .github/scripts/toolchain/build-cocom.sh, .github/scripts/toolchain/build-cygwin.sh, .github/scripts/toolchain/build-gcc-stage1.sh, .github/scripts/toolchain/build-gcc.sh, .github/scripts/toolchain/build-mingw-crt.sh, .github/scripts/toolchain/build-mingw-headers.sh, .github/scripts/toolchain/build-mingw-winpthreads.sh, .github/scripts/toolchain/build-mingw.sh, .github/workflows/advanced.yml, .github/workflows/main.yml
Enabling ccache on `advanced.yml` revealed that we are reaching disk space limit of the default GHA runners for `x86_64-pc-cygwin` build (https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/actions/runs/10283146312/job/28456360182). This PR will save some space by deleting build folders of individual components after they succesfully build.
=> Delete build folders after successful builds

.github/workflows/main.yml
The change is needed to check if tests can be built on bootstrapping. It will be useful to use aarch64 runners to validate it.
=> Build tests in the main workflow

.github/scripts/toolchain/execute-gcc-tests.sh, .github/scripts/toolchain/wsl-sim.exp
This PR has non-observable effect on x64 testing (https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/actions/runs/10307874341) because the host system already contains x64 assembler but fixes test failures when x64 assembler is used for aarch64 testing. In other words, it prefers binutils produced by the build over the sytem ones.
Allows to run native tests using WSL interop increasing the number of tests executed from ~400k to ~800k and fixes test failures like:
```
Executing on host: /root/mingw-woarm64-build/build-aarch64-w64-mingw32-msvcrt/gcc/gcc/xgcc -B/root/mingw-woarm64-build/build-aarch64-w64-mingw32-msvcrt/gcc/gcc/    -fdiagnostics-plain-output    -O1  -w -c -o pr106433.o /root/mingw-woarm64-build/code/gcc-master/gcc/testsuite/gcc.c-torture/compile/pr106433.c …
```
=> Fixes of aarch64 testing in WSL environment

.github/scripts/install-dependencies.sh, .github/scripts/toolchain/execute-gcc-tests.sh
There is no `--target-board` option of the `runtest` executable, the correct syntax is `--target_board=board_name`. Also, without `autogen` installed the target tests complain that `autogen` is missing.
=> Fix GCC target tests execution

tools/find_symbol.py
This script can find symbol in any binary file in the specified folder using the specified `<target>-nm`.
=> Add utility script for "undefined symbol" issues debugging

.github/scripts/config.sh, .github/scripts/update-sources.sh
Passing the branches parameters is not working for [https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/actions/workflows/test-toolchain.yml](https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/actions/workflows/test-toolchain.yml) workflow. This PR fixes that.
Tested by https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/actions/runs/10816924634/job/30009164947.
=> Fix how source code repositories branches are specified

.github/scripts/config.ps1, .github/scripts/config.sh, .github/scripts/ffmpeg/unpack-tests.ps1, .github/scripts/libjpeg-turbo/unpack-tests.ps1, .github/scripts/openblas/unpack-tests.ps1, .github/scripts/openssl/unpack-tests.ps1, .github/scripts/tests/build.sh, .github/scripts/tests/pack.sh, .github/scripts/tests/unpack.ps1, .github/scripts/toolchain/build-gcc.sh, .github/scripts/toolchain/build-mingw-crt.sh, .github/scripts/toolchain/build-mingw-winpthreads.sh, .github/scripts/toolchain/build-mingw.sh, .github/scripts/toolchain/pack-runtime-mock.sh, .github/scripts/toolchain/pack-runtime.sh, .github/scripts/toolchain/unpack-runtime.ps1, .github/scripts/zlib/unpack.ps1, .github/workflows/advanced.yml
After Windows-on-ARM-Experiments/gcc-woarm64#21 was merged, shared `libgcc` can be enabled for `aarch64-w64-mingw32`.
=> Shared `libgcc` can now be enabled for `aarch64-w64-mingw32`

.github/scripts/update-sources.sh
Since `.github/scripts/update-sources.sh` is doing `--single-branch` clone, switching to any other branch fails as the other branch do no exists locally. This PR check whether the branch exsits and adds it to the local index before actual switch.
=> Fix switch to another git branch

.github/scripts/toolchain/patch-cygwin.sh, .github/workflows/rebase.yml, patches/cygwin/0003-fix-mingw.patch
Adds daily rebase of Cygwin to `rebase.yml`.
Also fixes the current daily rebase failure for `x86_64-pc-cygwin` target.
=> Add daily rebase of Cygwin to `rebase.yml`

.github/scripts/toolchain/build-mingw-crt.sh, .github/scripts/toolchain/build-mingw-winpthreads.sh, .github/scripts/toolchain/build-mingw.sh
There does not seem to be `--enable-debug` option in the MinGW build scripts.
=> Fix enabling debug build for MinGW

.github/workflows/advanced.yml, .github/workflows/main.yml
Unifies artifact naming, fixes issue that if more than one build variant fails, only one build artifact is uploaded.
=> Fix naming of artifacts

tools/find-regression-run.sh, tools/find-regression.sh
So far this script is intended to be run manually:
```
tools/find-regression.sh gcc
```
with repository name as a single argument.
In the future, this can be extended to find regression in all the repositories (binutils, GCC, MinGW, Cygwin) and triggered automatically when daily updates workflow encounters build failure.
=> Add script for finding build regression using `git bisect`

.github/scripts/install-dependencies.sh, .github/scripts/toolchain/build-gcc-stage1.sh, .github/scripts/toolchain/build-gcc.sh
Enables build of D, LTO, m2, ObjC, and Obj-c++ languages. The remaining languages, Ada, Go, and JIT, are harder to bootstrap for two stage cross-compilation build so it would be easier to test them on native toolchain.
Depends on Windows-on-ARM-Experiments/gcc-woarm64#33.
=> Enable more languages for better test coverage

.github/scripts/openblas/build.sh, .github/scripts/rebase-start.sh, .github/scripts/toolchain/patch-cygwin.sh, patches/cygwin/0005-fix-winsup-gcc-15.patch, tests/CMakeLists.txt
The root cause of both Cygwin and OpenBLAS build issues was that GCC sets `-std=gnu23` by default. OpenBLAS build was fixed by setting `-std=gnu17` explicitly while Cygwin build was fixed by removing old-style function declarations.
=> Fix daily rebase after patch series 3 has been upstreamed

.github/workflows/rebase.yml
The former one is not that fresh as it was originally expected.
=> Fix the upstream Cygwin git repository URL

.github/workflows/advanced.yml, .github/workflows/rebase.yml
This change was forgotten when https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/pull/204 has been done.
Tested by https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/actions/runs/12182962755 (the release was already deleted)
=> Fix release after `advanced.yml` was refactored to build runtime package

.github/scripts/config.sh, .github/scripts/update-sources.sh
I just learned hard that doing flat clones of the dependent repositories (to gain some speed up) is pretty dangerous and should not be default for local builds.
=> Add possibility to do full clone of dependent repositories

.github/scripts/config.sh, .github/scripts/update-sources.sh
If `REBASE_SOURCES` is set to `1` in `config.sh` the `update-sources.sh` can be used to rebase feature branches of the dependencies repositories to their corresponding development branches. This is handy for keeping PRs like https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/pull/123 up-to-date on a daily basis.
=> Add posibility to rebase feature branches to development branches to `update-sources.sh`

.github/scripts/config.sh, .github/workflows/advanced.yml
Cocom started failing in all CI runs.
Run cd /home/runner/work/mingw-woarm64-build/mingw-woarm64-build/code
Cloning into 'cocom'...
fatal: unable to access 'https://git.code.sf.net/p/cocom/git/': server certificate verification failed. CAfile: none CRLfile: none
=> Change Cocom repo URL

.github/scripts/binutils/build.sh, .github/scripts/toolchain/build-cygwin.sh, .github/scripts/toolchain/build-gcc.sh, .github/scripts/toolchain/build-mingw-crt.sh, .github/workflows/advanced.yml
This PR contains experiment to build `aarch64-pc-cygwin` toolchain capable of building working "Hello World" executable. The vast majority of Cygwin codebase that needs to be ported to Arm64 is not implemented though.
=> Add `aarch64-pc-cygwin` target to `advanced.yml`

.github/workflows/rebase.yml
Fixes missing specification of Cygwin branch in the `rebase.yml` workflow file. Also, tests whether the new branch protection rules on `rebase-upstream` branches are not failing the daily rebase.
=> Fix Cygwin branch for daily rebase

tests/math-test.c, tests/math-test.cpp
Tests bit size of `float`, `double`, `long double` and `_Float128`. Tests functionality of `float`, `double` and `long double` with `printf` and keeps separate test for `_Float128` because we don't support its printing yet.
Validates change of `long double` from 128bit to 64bit which was done in https://github.com/Windows-on-ARM-Experiments/gcc-woarm64/pull/3
Removes unused `math-test.cpp`
Based on https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build/pull/24
=> Add tests for `float`, `double` and `long double` support

.github/workflows/advanced.yml
The path to the cached files is part of the internal cache key. This is a problem when the the source and destination runners have different operating systems. This can be fixed by using relative paths to cached files.
=> Use relative toolchain path to fix caching between different host OS runners

.github/scripts/binutils/build.sh
This allows easier transfer of the toolchain between different build environments for `aarch64-pc-cygwin` target. The `aarch64-w64-mingw32` builds binutils with static libraries already. For example, without this change, when the toolchain is built on `ubuntu-22.04-arm` runner and then transferred to Arm64 WSL with Ubuntu-22.04, `$TOOLCHAIN_PATH/$HOST/$TARGET/lib` needs to be added to `LD_LIBRARY_PATH`.
=> Disable shared libraries build for `aarch64-pc-cygwin` target binutils

.github/scripts/toolchain/build-mingw-crt.sh, .github/scripts/toolchain/execute-cygwin-tests.sh
This PR introduces a new script, `cygwin-test-suite.sh`, to build and run the internal test suite present in the `Cygwin winsup` directory. 
- Added `cygwin-test-suite.sh` to build & execute the test suite.
- Updated build.sh to conditionally invoke the test suite when `CYGWIN_TESTSUITE=1` and platform is set to Cygwin.
- Introduced `CYGWIN_TESTSUITE` configuration variable in config.sh (default: enabled).
=> Add script for Cygwin testing

.github/workflows/advanced.yml, .github/workflows/main.yml
It's more convenient to build `aarch64-*` toolchains for `aarch64-pc-linux` host for transferring the toolchians to WSL-capable Arm64 GitHub Actions runners becase Arm64 WSL cannot run x64 Linux binaries.
- It seems that build times of such builds is comparable or maybe slightly faster than before (when `ccache` is filled).
=> Build `aarch64-*` toolchans for `aarch64-pc-linux` host

.github/scripts/toolchain/build-cocom.sh
COCOM codebase is not compatible with GCC15 as it uses partical declarations. This PR forces GNU89 standard for COCOM build. It's needed for build of Cygwin x64 -> Cygwin Arm64 cross-compiler in Cygwin shell.
=> Fix build of COCOM with GCC15

.github/scripts/binutils/build.sh
Removes configure options of binutils that were added compared to the upstream recipes as workarounds to build `aarch64-pc-cygwin` target binutils that no longer seems to be needed. Removal of `--disable-sim` requires and validates https://github.com/Windows-on-ARM-Experiments/binutils-woarm64/pull/8.
=> Remove configure options that are no longer needed to build Cygwin binutils

.github/scripts/toolchain/build-cygwin.sh
Requires and tests Windows-on-ARM-Experiments/newlib-cygwin#21.
=> Enable `cygserver` for stage 2 build

.github/scripts/build.sh, .github/scripts/toolchain/build-mingw-headers.sh, .github/workflows/advanced.yml
Fix Cygwin toolchain build to be compatible with upstream workflow.
Based on https://cygwin.com/cgit/cygwin-packages/w32api-headers/tree/w32api-headers.cygport
Requires https://github.com/Windows-on-ARM-Experiments/newlib-cygwin/pull/29
=> Fix Cygwin toolchain build to be compatible with upstream workflow

.github/scripts/toolchain/build-cygwin.sh
Workaround removing build of `utils` in Cygwin codebase was removed with `--disable-utils` `configure` option.
=> Use `--disable-utils` for stage1 Cygwin build
